// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Game struct {
	ID            uuid.UUID          `json:"id"`
	Player1ID     uuid.UUID          `json:"player1_id"`
	Player2ID     *uuid.UUID         `json:"player2_id"`
	Board         []byte             `json:"board"`
	Status        string             `json:"status"`
	CurrentTurn   *uuid.UUID         `json:"current_turn"`
	WinnerID      *uuid.UUID         `json:"winner_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Player1Symbol int32              `json:"player1_symbol"`
	Player2Symbol int32              `json:"player2_symbol"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	Login     string             `json:"login"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
