// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAvailableGames = `-- name: GetAvailableGames :many
SELECT id,
       player1_id,
       player2_id,
       board,
       status,
       current_turn,
       winner_id,
       created_at,
       updated_at,
       player1_symbol,
       player2_symbol
FROM games
WHERE status = 'waiting'
`

func (q *Queries) GetAvailableGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.Query(ctx, getAvailableGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Player1ID,
			&i.Player2ID,
			&i.Board,
			&i.Status,
			&i.CurrentTurn,
			&i.WinnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Player1Symbol,
			&i.Player2Symbol,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompletedGamesByUserID = `-- name: GetCompletedGamesByUserID :many
SELECT id,
       player1_id,
       player2_id,
       board,
       status,
       current_turn,
       winner_id,
       created_at,
       updated_at,
       player1_symbol,
       player2_symbol
FROM games
WHERE (status = 'draw' AND (player1_id = $1 OR player2_id = $1))
   OR (status = 'win' AND winner_id = $1)
`

func (q *Queries) GetCompletedGamesByUserID(ctx context.Context, player1ID uuid.UUID) ([]Game, error) {
	rows, err := q.db.Query(ctx, getCompletedGamesByUserID, player1ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Player1ID,
			&i.Player2ID,
			&i.Board,
			&i.Status,
			&i.CurrentTurn,
			&i.WinnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Player1Symbol,
			&i.Player2Symbol,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGame = `-- name: GetGame :one
SELECT id,
       player1_id,
       player2_id,
       board,
       status,
       current_turn,
       winner_id,
       created_at,
       updated_at,
       player1_symbol,
       player2_symbol
FROM games
WHERE id = $1
`

func (q *Queries) GetGame(ctx context.Context, id uuid.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, getGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Player1ID,
		&i.Player2ID,
		&i.Board,
		&i.Status,
		&i.CurrentTurn,
		&i.WinnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Player1Symbol,
		&i.Player2Symbol,
	)
	return i, err
}

const getTopPlayers = `-- name: GetTopPlayers :many
SELECT u.id                AS user_id,
       u.login,
       COALESCE(
               COUNT(*) FILTER (WHERE g.winner_id = u.id)::double precision
                   / NULLIF(COUNT(*) FILTER (WHERE g.status = 'draw')
                                + COUNT(*) FILTER (WHERE g.status = 'win' AND g.winner_id != u.id),
                            0)::double precision,
               0::double precision
       )::double precision AS win_ratio
FROM users u
         LEFT JOIN games g
                   ON g.player1_id = u.id OR g.player2_id = u.id
GROUP BY u.id, u.login
ORDER BY win_ratio DESC
LIMIT $1
`

type GetTopPlayersRow struct {
	UserID   uuid.UUID `json:"user_id"`
	Login    string    `json:"login"`
	WinRatio float64   `json:"win_ratio"`
}

func (q *Queries) GetTopPlayers(ctx context.Context, limit int) ([]GetTopPlayersRow, error) {
	rows, err := q.db.Query(ctx, getTopPlayers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopPlayersRow{}
	for rows.Next() {
		var i GetTopPlayersRow
		if err := rows.Scan(&i.UserID, &i.Login, &i.WinRatio); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, login, password, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, login, password, created_at
FROM users
WHERE login = $1
`

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const upsertGame = `-- name: UpsertGame :exec
INSERT INTO games (id, player1_id, player2_id, board, status, current_turn, winner_id,
                   created_at, updated_at, player1_symbol, player2_symbol)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO UPDATE SET player1_id     = EXCLUDED.player1_id,
                               player2_id     = EXCLUDED.player2_id,
                               board          = EXCLUDED.board,
                               status         = EXCLUDED.status,
                               current_turn   = EXCLUDED.current_turn,
                               winner_id      = EXCLUDED.winner_id,
                               created_at     = EXCLUDED.created_at,
                               updated_at     = EXCLUDED.updated_at,
                               player1_symbol = EXCLUDED.player1_symbol,
                               player2_symbol = EXCLUDED.player2_symbol
`

type UpsertGameParams struct {
	ID            uuid.UUID          `json:"id"`
	Player1ID     uuid.UUID          `json:"player1_id"`
	Player2ID     *uuid.UUID         `json:"player2_id"`
	Board         []byte             `json:"board"`
	Status        string             `json:"status"`
	CurrentTurn   *uuid.UUID         `json:"current_turn"`
	WinnerID      *uuid.UUID         `json:"winner_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Player1Symbol int32              `json:"player1_symbol"`
	Player2Symbol int32              `json:"player2_symbol"`
}

func (q *Queries) UpsertGame(ctx context.Context, arg UpsertGameParams) error {
	_, err := q.db.Exec(ctx, upsertGame,
		arg.ID,
		arg.Player1ID,
		arg.Player2ID,
		arg.Board,
		arg.Status,
		arg.CurrentTurn,
		arg.WinnerID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Player1Symbol,
		arg.Player2Symbol,
	)
	return err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (id, login, password, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET login      = EXCLUDED.login,
                               password   = EXCLUDED.password,
                               created_at = EXCLUDED.created_at
`

type UpsertUserParams struct {
	ID        uuid.UUID          `json:"id"`
	Login     string             `json:"login"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.Exec(ctx, upsertUser,
		arg.ID,
		arg.Login,
		arg.Password,
		arg.CreatedAt,
	)
	return err
}
