// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetAvailableGames(ctx context.Context) ([]Game, error)
	GetCompletedGamesByUserID(ctx context.Context, player1ID uuid.UUID) ([]Game, error)
	GetGame(ctx context.Context, id uuid.UUID) (Game, error)
	GetTopPlayers(ctx context.Context, limit int) ([]GetTopPlayersRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByLogin(ctx context.Context, login string) (User, error)
	UpsertGame(ctx context.Context, arg UpsertGameParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) error
}

var _ Querier = (*Queries)(nil)
